### ISSUE TITLE
iPhone 6 modal not triggering reliably

### ISSUE THREAD

**Issue by welcomebrand** [cferdinandi/modals#57] opened 2016-12-21 13:05 UTC
This one is a little odd, it seems that the modal script is struggling to trigger on iPhone 6's (specifically iPhone 6 / Safari). 

It does work sometimes but there doesn't seem to be a reliable situation where I can say it definitely doesn't work on xyz occasion. 

I've tested the modal on lots of other browsers on Windows, Mac and other phones - Android etc and it works exactly as intended and triggers the window fine. It even works fine on iPad / Safari so I'm at a loss and figured you might be able to suggest things to try at least! It also works in iPhone browser emulators so may be specific to actual device. 

Recreate: Visit https://olympicholidays.com on iPhone 6 / Safari (don't know if same happens on iPhone 7) and click the "Holiday Search" green button top right and a search form should load in a full screen modal. 

Any ideas on debugging/fixing certainly appreciated :) 

James.

**Comment by cferdinandi** [comment] 2016-12-23 01:11
I'm seeing it, too, and am able to consistently reproduce it, but can't isolate the cause at the moment.

I'm unable to reproduce it with the demo, though, which makes me think it's something about an interaction with another script or some customizations you've made.

When debugging stuff like this, I find it helpful to remove everything "non stock" and start adding back customizations 1x1 until the problem shows up again (at which point you've found the cause). Alternatively, you can remove stuff 1x1 until you find the cause, too.

As a policy, I generally don't provide individual support for specific implementation issues on my OSS projects, so I'm going to close this ticket. But I will take another look at it if I find time.

**Closed by cferdinandi** 2016-12-23 01:11 UTC

**Comment by cferdinandi** [comment] 2016-12-23 01:19
Ok, so look at this more closely, your minified output looks quite different from the [minified output of Modals](https://github.com/cferdinandi/modals/blob/5faa981972ca95c1e00a742b4af56e3c1752bdbf/dist/js/modals.min.js) (I linked to an older v9.x version, as I don't think you're using v10.x).

Specifically, I see references to `className` in your code that are missing from mine, and the error I'm seeing in the dev tools console is that there's no element found to ready the `className` value of. Your minifier seems either flawed or perhaps overly aggressive.
